import 'server-only'
import type { RepClassBreakdown } from './queries'

// Commission-model explainer for the rep scorecard: a short narrative telling
// the rep why their new-model commission out- or under-performed the
// deprecated 4%-flat-on-territory-revenue model. Steven's call (2026-07-04):
// generated by Claude Haiku via OpenRouter (raw REST — this repo cannot npm
// install new SDKs), with a deterministic fallback so the section always
// renders even when OPENROUTER_API_KEY is missing or the call fails.

export interface ExplainInput {
  repName: string
  monthLabel: string
  inPromoPeriod: boolean
  enrollments: number
  enrollmentGate: number
  qualifies: boolean
  breakdown: RepClassBreakdown
  baseRate: number
  bonusRate: number
  oldModelTotal: number
  newModelTotal: number
  delta: number
  counterfactualMessage: string | null
}

export interface CommissionExplanation {
  text: string
  source: 'ai' | 'fallback'
}

const OPENROUTER_URL = 'https://openrouter.ai/api/v1/chat/completions'
const OPENROUTER_MODEL = 'anthropic/claude-haiku-4.5'

function usd(value: number): string {
  return `$${Math.round(value).toLocaleString('en-US')}`
}

/** Deterministic explanation used when the AI call is unavailable. */
export function buildFallbackExplanation(input: ExplainInput): string {
  const parts: string[] = []
  const { breakdown } = input

  if (input.delta > 0.005) {
    parts.push(
      `In ${input.monthLabel} you earned ${usd(input.delta)} more than the old 4% flat model would have paid — ` +
        `your ${input.enrollments} new-customer enrollment${input.enrollments === 1 ? '' : 's'} cleared the ` +
        `${input.enrollmentGate}-enrollment gate, unlocking the extra ${(input.bonusRate * 100).toFixed(0)}% bonus ` +
        `on ${usd(breakdown.newWindowRevenue)} of new-business revenue.`
    )
  } else if (input.qualifies) {
    parts.push(
      `In ${input.monthLabel} you matched the old 4% flat model. You cleared the enrollment gate, but new-business ` +
        `revenue was ${usd(breakdown.newWindowRevenue)}, so the bonus added little on top of base commission.`
    )
  } else {
    const away = Math.max(0, input.enrollmentGate - input.enrollments)
    parts.push(
      `In ${input.monthLabel} you earned the same as the old 4% flat model — base commission is unchanged, and the ` +
        `new ${(input.bonusRate * 100).toFixed(0)}% bonus stayed locked because you landed ${input.enrollments} of the ` +
        `${input.enrollmentGate} new-customer enrollments needed (${away} more would have unlocked it).`
    )
  }

  const segments: string[] = []
  if (breakdown.recurringRevenue > 0) segments.push(`${usd(breakdown.recurringRevenue)} recurring`)
  if (breakdown.winBackRevenue > 0) segments.push(`${usd(breakdown.winBackRevenue)} winback`)
  if (breakdown.newWindowRevenue > 0) segments.push(`${usd(breakdown.newWindowRevenue)} new business`)
  if (segments.length > 0) {
    parts.push(`Your revenue mix was ${segments.join(', ')} — the ${(input.baseRate * 100).toFixed(0)}% base pays on all of it.`)
  }
  if (input.counterfactualMessage) parts.push(input.counterfactualMessage)
  if (!input.inPromoPeriod) {
    parts.push('This month is outside the Q3 promo, so these are reference figures, not payable commissions.')
  }
  return parts.join(' ')
}

/**
 * Ask Claude Haiku (via OpenRouter) for the narrative. Returns null on any
 * failure — missing key, timeout, non-2xx, malformed body — so callers can
 * fall back deterministically.
 */
async function fetchHaikuExplanation(input: ExplainInput): Promise<string | null> {
  const apiKey = process.env.OPENROUTER_API_KEY
  if (!apiKey) return null

  const system =
    'You write 3-4 sentence commission explanations for MedShip sales reps. ' +
    'Context: reps are transitioning from a legacy flat 4% commission on all territory revenue to a new model: ' +
    '4% base on all attributed revenue PLUS a 2% bonus on new-customer revenue that unlocks only when the rep ' +
    'enrolls at least the gate number of first-ever customers that month. The base is identical to the old model, ' +
    'so the delta vs the old model is the bonus. Explain, using the JSON figures provided, why this rep out- or ' +
    'under-performed the old model this month, and what single action would most improve next month. ' +
    'Be direct, factual, and motivating — never invent numbers, never shame, no emoji, no greeting, no preamble. ' +
    'If the month is outside the promo period, note the figures are reference-only. Plain text only.'

  try {
    const response = await fetch(OPENROUTER_URL, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: OPENROUTER_MODEL,
        max_tokens: 400,
        messages: [
          { role: 'system', content: system },
          { role: 'user', content: JSON.stringify(input) },
        ],
      }),
      signal: AbortSignal.timeout(12_000),
    })
    if (!response.ok) return null

    const payload = (await response.json()) as {
      choices?: Array<{ message?: { content?: string | null } }>
    }
    const text = payload.choices?.[0]?.message?.content?.trim()
    return text && text.length > 0 ? text : null
  } catch {
    return null
  }
}

export async function getCommissionExplanation(input: ExplainInput): Promise<CommissionExplanation> {
  const aiText = await fetchHaikuExplanation(input)
  if (aiText) return { text: aiText, source: 'ai' }
  return { text: buildFallbackExplanation(input), source: 'fallback' }
}
