import 'server-only'
import type { RepCohortBreakdown } from './queries'

// Commission-model explainer for the rep scorecard: a short narrative telling
// the rep why their tiered-model commission out- or under-performed the
// deprecated 4%-flat-on-territory-revenue model. Steven's call (2026-07-04):
// generated by Claude Haiku via OpenRouter (raw REST — this repo cannot npm
// install new SDKs), with a deterministic fallback so the section always
// renders even when OPENROUTER_API_KEY is missing or the call fails.
//
// Model (2026-07-04 revision): NEW cohort revenue pays newRate (6%), WINBACK
// pays winbackRate (5%), RECURRING pays a tier set by the month's NEW-customer
// enrollments — full (4%) at the gate, partial (3%) at 1, floor (2%) at 0.
// The plan CAN pay less than the old flat 4% — that penalty must be stated
// plainly, never spun.

export interface ExplainInput {
  repName: string
  monthLabel: string
  inPromoPeriod: boolean
  enrollments: number
  enrollmentGate: number
  qualifies: boolean
  recurringRate: number
  rates: {
    new: number
    winback: number
    recurringFull: number
    recurringPartial: number
    recurringZero: number
    legacyFlat: number
  }
  breakdown: RepCohortBreakdown
  commissions: {
    new: number
    winback: number
    recurring: number
    total: number
  }
  oldModelTotal: number
  delta: number // total - oldModelTotal; negative = quota penalty
  counterfactualMessage: string | null
}

export interface CommissionExplanation {
  text: string
  source: 'ai' | 'fallback'
}

const OPENROUTER_URL = 'https://openrouter.ai/api/v1/chat/completions'
const OPENROUTER_MODEL = 'anthropic/claude-haiku-4.5'

function usd(value: number): string {
  return `$${Math.round(Math.abs(value)).toLocaleString('en-US')}`
}

function pct(rate: number): string {
  const value = rate * 100
  return `${Number.isInteger(value) ? value.toFixed(0) : value.toFixed(1)}%`
}

/** Deterministic explanation used when the AI call is unavailable. */
export function buildFallbackExplanation(input: ExplainInput): string {
  const parts: string[] = []
  const { breakdown, rates } = input
  const away = Math.max(0, input.enrollmentGate - input.enrollments)

  if (input.delta > 0.005) {
    parts.push(
      `In ${input.monthLabel} you earned ${usd(input.delta)} more than the old ${pct(rates.legacyFlat)} flat model — ` +
        `the premium rates on ${usd(breakdown.newRevenue)} of new business (${pct(rates.new)}) and ` +
        `${usd(breakdown.winbackRevenue)} of winbacks (${pct(rates.winback)}) outweighed ` +
        (input.qualifies
          ? `nothing: your ${input.enrollments} enrollments also held recurring at the full ${pct(rates.recurringFull)}.`
          : `the recurring-rate penalty (${pct(input.recurringRate)} instead of ${pct(rates.recurringFull)} at ${input.enrollments} enrollment${input.enrollments === 1 ? '' : 's'}).`)
    )
  } else if (input.delta < -0.005) {
    parts.push(
      `In ${input.monthLabel} you earned ${usd(input.delta)} LESS than the old ${pct(rates.legacyFlat)} flat model. ` +
        `With ${input.enrollments} of the ${input.enrollmentGate} new-customer enrollments required, your recurring rate ` +
        `dropped to ${pct(input.recurringRate)} on ${usd(breakdown.recurringRevenue)} of recurring business — that penalty ` +
        `outweighed the premium rates on new (${pct(rates.new)}) and winback (${pct(rates.winback)}) revenue.`
    )
  } else {
    parts.push(
      `In ${input.monthLabel} you came out roughly even with the old ${pct(rates.legacyFlat)} flat model — the premium ` +
        `on new/winback revenue and the recurring rate of ${pct(input.recurringRate)} balanced out.`
    )
  }

  if (away > 0) {
    parts.push(
      `${away} more enrollment${away === 1 ? '' : 's'} would restore the full ${pct(rates.recurringFull)} on your recurring book.`
    )
  }
  if (input.counterfactualMessage && away > 0) parts.push(`${input.counterfactualMessage}.`)
  if (!input.inPromoPeriod) {
    parts.push('This month is outside the Q3 promo, so these are reference figures, not payable commissions.')
  }
  return parts.join(' ')
}

/**
 * Ask Claude Haiku (via OpenRouter) for the narrative. Returns null on any
 * failure — missing key, timeout, non-2xx, malformed body — so callers can
 * fall back deterministically.
 */
async function fetchHaikuExplanation(input: ExplainInput): Promise<string | null> {
  const apiKey = process.env.OPENROUTER_API_KEY
  if (!apiKey) return null

  const system =
    'You write 3-4 sentence commission explanations for MedShip sales reps. ' +
    'Context: reps moved from a legacy flat 4% commission on all territory revenue to a tiered model: ' +
    '6% on new-business revenue (first 365 days after enrolling a first-ever customer), 5% on winback revenue ' +
    '(first 365 days after reviving a 365+ day lapsed customer), and a variable rate on recurring revenue set by ' +
    'that month\'s NEW-customer enrollments — 4% at the enrollment quota, 3% at one enrollment, 2% at zero. ' +
    'The tiered model CAN pay less than the old flat model when the quota is missed: state that penalty plainly ' +
    'and quantify it from the JSON — never claim the new model always pays at least as much. ' +
    'Explain, using the JSON figures only, why this rep out- or under-performed the old model this month, and what ' +
    'single action would most improve next month (usually: enroll new customers to protect the recurring rate). ' +
    'Be direct, factual, and motivating — never invent numbers, never shame, no emoji, no greeting, no preamble. ' +
    'If the month is outside the promo period, note the figures are reference-only. Plain text only.'

  try {
    const response = await fetch(OPENROUTER_URL, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: OPENROUTER_MODEL,
        max_tokens: 400,
        messages: [
          { role: 'system', content: system },
          { role: 'user', content: JSON.stringify(input) },
        ],
      }),
      signal: AbortSignal.timeout(12_000),
    })
    if (!response.ok) return null

    const payload = (await response.json()) as {
      choices?: Array<{ message?: { content?: string | null } }>
    }
    const text = payload.choices?.[0]?.message?.content?.trim()
    return text && text.length > 0 ? text : null
  } catch {
    return null
  }
}

export async function getCommissionExplanation(input: ExplainInput): Promise<CommissionExplanation> {
  const aiText = await fetchHaikuExplanation(input)
  if (aiText) return { text: aiText, source: 'ai' }
  return { text: buildFallbackExplanation(input), source: 'fallback' }
}
